#+TITLE: Readme
** Description
Interpreters implemented after reading https://craftinginterpreters.com/.

** Some commands
To generate Expressions and Statements classes run:
#+begin_src bash
make genast
#+end_src

Run jlox (Java based) interpreter: 
#+begin_src bash
make jlox
#+end_src

Optionally you can provide an example file (the lookup directory is examples/, file extension is assumed to be .lox)
#+begin_src bash
make jlox f=closure
#+end_src

Run clox (C based) bytecode VM: 
#+begin_src bash
make clox
#+end_src

If you want to understand how commands are implemented and what are other options, refer to Makefile.


** Some notes
|----------------------------+-----------------+-------------------|
| Terminology                | Lexical grammar | Syntactic grammar |
|----------------------------+-----------------+-------------------|
| The “alphabet” is...       | Characters      | Tokens            |
| A “string” is...           | Lexeme or token | Expression        |
| It's implemented by the... | Scanner         | Parser            |
|----------------------------+-----------------+-------------------|

John Backus and company needed a notation for specifying ALGOL 58 and came up with Backus-Naur form. Since then, nearly everyone uses some flavor of BNF


*** Expression problem
OOP:
Easy to add new class. Difficult to add new method.

|--------+---------+---------|
| Class1 | method1 | method2 |
|--------+---------+---------|
| Class2 | method1 | method2 |
|--------+---------+---------|
| Class3 | method1 | method2 |
|--------+---------+---------|

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|----------+---------+---------+---+---|
| NewClass | method1 | method2 |   |   |
|----------+---------+---------+---+---|

FP:
Easy to add new method/function. Difficult to add new class/type.

|-----------+-----------+---+-----------|
| function1 | function2 | < | function3 |
|-----------+-----------+---+-----------|
| Type1     | Type1     | < | Type1     |
|-----------+-----------+---+-----------|
| Type2     | Type2     | < | Type2     |
|-----------+-----------+---+-----------|

#+begin_quote
A bunch of smart language nerds noticed that neither style made it easy to add both rows and columns to the table. They called this difficulty the “expression problem” because—like we are now—they first ran into it when they were trying to figure out the best way to model expression syntax tree nodes in a compiler.
#+end_quote

** Copyright
Code is mostly copied (with some modification and notes) from the book, for original copyright please visit the website above.
